name: Test Compile

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Create Source File
      shell: bash
      run: echo -e "#include <stdio.h>\n\nint main()\n{\n    printf('Hello, World');\n    return 0;\n}" > source.c
    - name: Build
      run: gcc source.c -o test.exe
    - name: Run
      run: .\test.exe
