name: Test Compile

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: gcc 'src\windows_installer\myofinder.cpp' -lshlwapi -o 'bin\myofinder.exe'
    - name: Check If Built
      shell: cmd
      run: dir bin
