# Installs the Python dependencies, installs MyoFInDer, and checks that it works as expected
name: Test Python Package

on:
  # Runs on pull requests targeting the default branch
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: ["main"]

  # May also be started manually
  workflow_dispatch:

  # Runs automatically every first day of the month
  schedule:
    - cron: '0 12 1 * *'

jobs:
  test-python-package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Run on all the supported Python versions
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        # Run on all the supported platforms
        os: [ubuntu-latest, windows-latest, macos-latest]
        # Tests fail because some dependencies have to be built
        exclude:
          - os: windows-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.14"
          - os: ubuntu-latest
            python-version: "3.14"
          - os: macos-latest
            python-version: "3.13"
          - os: macos-latest
            python-version: "3.14"

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v5
    # Set up the correct version of Python
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    # Install the build dependencies
    - name: Install Dependencies
      run: python -m pip install --upgrade pip wheel build setuptools
    # Install the MyoFInDer Python module
    - name: Install MyoFInDer
      run: python -m pip install .
    # On Windows, MyoFInDer can run even though there is no graphical environment
    # Running the unit tests to check that everything's working as expected
    - name: Test MyoFInDer (Windows)
      if: runner.os == 'Windows'
      run: |
        $Env:MYOFINDER_GITHUB_ACTION = 1
        python -m unittest -v tests
      # On Linux, the Xvfb virtual X server can be used
      # Therefore, it is possible to run the automated test suite
    - name: Import MyoFInDer (Linux)
      if: runner.os == 'Linux'
      run: |
        export DISPLAY=:99
        export MYOFINDER_GITHUB_ACTION=:1
        Xvfb :99 -screen 0 1920x1080x24 & python -m unittest -v tests
    # On macOS, it is not possible to set up a virtual graphical environment
    # Therefore, no automated tests can be run on macOS
    - name: Import MyoFInDer (macOS)
      if: runner.os == 'macOS'
      run: |
        python -c "import myofinder;print(myofinder.__version__)"
